import {readFile,writeFile,mkdir} from 'node:fs/promises';
import {designMetrics,cosine} from '../quality/metrics.js';
const read=async p=>JSON.parse(await readFile(p,'utf8'));
const campaign=await read('data/des2/campaign.json'),proof=await read('data/des2/proof.json'),machine=await read('data/quality/machine.json'),designs=await read('data/quality/designs.json'),robustness=await read('data/des2/robustness.json');
const esc=s=>String(s).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const mean=a=>a.reduce((n,x)=>n+x,0)/Math.max(1,a.length),percent=n=>Math.round(n*100)+'%';
const rows=campaign.levels.map(l=>({id:l.id,...designMetrics(l)}));
for(const r of rows)r.nearestSimilarity=Math.max(...rows.filter(q=>q!==r).map(q=>cosine(q.tiles,r.tiles)));
const stats=sets=>Object.entries(sets).map(([name,rs])=>({name,count:rs.length,packed:mean(rs.map(r=>r.metrics?.packedFraction??r.packedFraction)),nearest:mean(rs.map(r=>r.metrics?.nearestSimilarity??r.nearestSimilarity))}));
const table=stats({...designs,des2:rows});
const colors={orange:'#ff963c',blue:'#42dce6',bumper:'#76a6ff',bombMagnet:'#ec6cdd',obstacle:'#93a5b2',portalBlue:'#46daee',portalOrange:'#ff9745'};
function draw(level){return `<svg viewBox="0 0 400 600" role="img" aria-label="Схема ${esc(level.id)}"><rect width="400" height="600" fill="#08121e"/><circle cx="200" cy="40" r="8.5" fill="white"/>${level.pegs.map(p=>{
 const c=colors[p.type]||'#ccc',angle=(p.angle||0)*180/Math.PI;
 if(p.type.startsWith('portal'))return `<path d="M${-17*p.portalScale} 0H${17*p.portalScale}" transform="translate(${p.x} ${p.y})rotate(${angle})" stroke="${c}" stroke-width="5"/>`;
 const field=p.type==='bombMagnet'?`<circle cx="${p.x}" cy="${p.y}" r="${p.magnetRadius}" fill="none" stroke="#77386c"/>`:'';
 if(p.shape!=='brick')return field+`<circle cx="${p.x}" cy="${p.y}" r="${(level.radius||8.5)*(p.bumperScale||1)}" fill="${c}"/>`;
 if(p.curveSlices)return `<path d="M${p.curveSlices.map(s=>s.x+','+s.y).join('L')}" fill="none" stroke="${c}" stroke-width="${p.height}"/>`;
 return `<rect x="${-p.width/2}" y="${-p.height/2}" width="${p.width}" height="${p.height}" fill="${c}" transform="translate(${p.x} ${p.y})rotate(${angle})"/>`;
 }).join('')}${(level.paths||[]).filter(p=>p.length>1).map(p=>`<path d="M${p.map(p=>p.x+','+p.y).join('L')}" fill="none" stroke="#fff3a5" stroke-width="1"/>`).join('')}</svg>`;}
const cards=campaign.levels.map(l=>{const r=proof.accepted.find(r=>r.id===l.id),p=r.proof,m=r.metrics,g=l.metadata.generator,b=robustness.rows.find(r=>r.id===l.id);
 return `<article><a href="/des2?id=${encodeURIComponent(l.id)}">${draw(p.frames[0])}<h3>${esc(l.name)}</h3></a><small>${m.pegs} пегов · ${m.targets} целей · ${p.shots} выстрелов у робота</small><p>Seed: <code>${esc(g.seed)}</code> · плотность ${g.density.toFixed(2)} · разрушение ${g.destruction.toFixed(2)}</p><details><summary>Настоящий проход и влияние механики</summary><div class="frames">${[p.frames[0],p.frames[1],p.frames.at(-1)].map(f=>`<figure>${draw(f)}<figcaption>После ${f.turn} выстрелов</figcaption></figure>`).join('')}</div><p>Полная очистка и повтор: ${p.complete&&p.replayComplete?'да':'нет'}. Лучший первый из девяти: ${percent(p.peakFirstFraction)} целей. Переносов шара через порталы: ${p.portalTeleports||0}.</p><p>Тот же маршрут с отключённой ведущей механикой: ${percent(b.removed.coverage)} очистки. Это проверяет вклад в данный маршрут, а не обязательность механики.</p><p>Смена момента старта и случайного потока без переприцеливания: ${b.holdouts.map(r=>percent(r.coverage)).join(' / ')}. Адаптивный поиск на другом старте: ${b.adaptive?percent(b.adaptive.coverage):'не запускался'}.</p><p>Углы от горизонтали, радианы: <code>${p.angles.map(a=>a.toFixed(5)).join(', ')}</code>.</p></details></article>`;
}).join('');
const before=machine.sets.des1,oldPeaks=before.filter(r=>r.peakFirstFraction>=.45).length;
const metricRows=table.map(r=>`<tr><td>${esc(r.name)}</td><td>${r.count}</td><td>${percent(r.packed)}</td><td>${r.nearest.toFixed(3)}</td></tr>`).join('');
const html=`<!doctype html><html lang="ru"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>Alea · аудит генерации / des2</title><style>body{margin:0;background:#06101a;color:#d2e7f2;font:15px/1.65 system-ui}main{max-width:1150px;margin:auto;padding:28px 18px}a{color:#77dfee}nav{display:flex;gap:18px;flex-wrap:wrap}h1{font-size:clamp(30px,7vw,48px);line-height:1.1}p{max-width:900px;color:#b4cbd8}.grid{display:grid;grid-template-columns:repeat(auto-fit,minmax(245px,1fr));gap:18px}article{border:1px solid #294452;border-radius:14px;padding:14px;background:#0a1a27}article svg{width:100%;max-height:410px}h3{font-size:16px}small{color:#6ed0dc}code{overflow-wrap:anywhere}summary{cursor:pointer;color:#8be1ed}figure{margin:0}figcaption{text-align:center;font-size:11px}.frames{display:grid;grid-template-columns:repeat(3,1fr);gap:5px}.frames svg{max-height:270px}table{border-collapse:collapse;margin:20px 0}td,th{padding:8px 15px;border-bottom:1px solid #294452;text-align:left}.audit{width:100%;height:auto}.gallery{display:grid;gap:14px}details{margin:14px 0}</style></head><body><main><nav><a href="/des2">Играть в /des2</a><a href="/des1">/des1</a><a href="/des">/des</a><a href="/gen">/gen</a><a href="/">Основная Alea</a></nav><h1>Генерация с позиции игрока</h1><p>Посмотрены все 292 схемы Blast, 11 уровней /des1, восемь различных композиций /des, восемь /gen, 19 различных уровней из основного CDN-снимка и пять из свежего локального экспорта основной пачки. Схемы ниже показывают геометрию; игра использует текущую продовую графику. Ручной игры и computer use в этом аудите не было.</p>
<h2>Что действительно мешало</h2><p>В /des1 повторяются две колонки с близкими вертикальными позициями. 97% обычных круглых пегов имеют соседа ближе диаметра плюс 3 px. Это локальная теснота куч, хотя вокруг них много пустого места. Машина после исправления стенда полностью прошла ${before.filter(r=>r.complete).length}/${before.length} уровней за 3–6 выстрелов; ${oldPeaks}/11 уровней допускают очистку не менее 45% целей одним из девяти начальных выстрелов. Проходимость есть, но часто ритм — один большой обвал и короткая зачистка. Чаши можно обойти прямым выстрелом в соседнюю нижнюю кучу: дизайнерская последовательность не всегда становится привлекательным маршрутом.</p><p>Число seed-вариантов плохо измеряет разнообразие. Основная Alea использует разные силуэты, кривые на ширину доски, движение и отдельные механические сцены. Blast полезен как словарь волн, дуг, колец, проходов и осей композиции. Фигурные рисунки вроде гитары и морковки не стоит автоматически смешивать в каждом уровне.</p>
<h2>Что перенесено в /des2</h2><p>Генератор выбирает пространственную схему, ведущую механику и параметры, строит непрерывные Bézier-ленты с настоящими деформированными кирпичами, распределяет цели по высоте, затем проверяет реальные полигоны и движение. Шесть схем: река, веер, острова, воронка, серпантин и орбита. Пять ведущих механик: рикошеты, магнит, порталы, движение и небольшое разрушение. Радиус шара и пегов 8.5 px, кирпич 34 × 10.2 px. Малые нагрузки — обычные сбиваемые пеги на сбиваемых опорах; серые оболочки не добавляются.</p><p>Магнит в этом движке влияет на подвижные пеги и конструкции, а не на белый шар. Поэтому магнитная сцена обязана иметь груз в поле. Порталы ловят нижние траектории и возвращают шар выше; кандидат должен продемонстрировать перенос с полезными попаданиями. Полный набор механик не добавляется в каждый уровень.</p><p>Из ${proof.accepted.length+proof.rejected.length+(JSON.parse(await readFile('data/des2/candidates.json','utf8')).results.length-proof.accepted.length)} кандидатов выбраны ${campaign.levels.length}. Каждый имеет найденный и повторённый полный проход в настоящем Game: ${Math.min(...proof.accepted.map(r=>r.proof.shots))}–${Math.max(...proof.accepted.map(r=>r.proof.shots))} выстрелов. Отбор сначала покрывает разные схемы, затем предпочитает удалённые пространственные распределения с ограничением повторов механик. В паузе «Новый уровень» можно менять схему, механику, плотность, долю разрушения и seed. Новые варианты проходят геометрию и короткую нативную проверку; полный поиск выполняется для каталога офлайн.</p>
<h2>Измерения и их границы</h2><table><thead><tr><th>Набор</th><th>Уровней</th><th>Тесные круги</th><th>Похожесть ближайшего</th></tr></thead><tbody>${metricRows}</tbody></table><p>«Тесные круги»: доля обычных круглых пегов с ближайшим соседом ближе 2r + 3 px. Похожесть — cosine по числу объектов в сетке 8 × 12; 1 означает одинаковое распределение, а не одинаковый геймплей. Для /des1 и /des2 физический масштаб совпадает. Blast имеет другой масштаб, поэтому его число — описание дампа, не рейтинг качества. main — 19 уровней CDN-снимка, latest — отдельный локальный экспорт пяти уровней; это разные срезы.</p><p>Машина начинает после 3 s, сравнивает девять первых углов, дальше ранжирует 61/181 углов нативным preview и проверяет лучшие полным Game с гравитацией, коллизиями, таймерами и движением. На выстрел отводится 22 s, между выстрелами 1.5 s. Preview не умеет предсказывать всю изменяющуюся сцену и останавливается на порталах. Победный маршрут воспроизводится независимо с тем же случайным потоком; он доказывает наличие прохода для этого старта, а не гарантирует человеческий результат.</p><p>Первая версия стенда не продвигала финальное замедление из Game.loop и ложно отбрасывала успешное последнее попадание как timeout. Указанные здесь результаты пересчитаны с настоящим драйвером времени. Вторая слабость — грубый подбор угла для одиночной цели — исправлена более плотными предложениями.</p>
<h2>Следующие точки роста</h2><ol><li>Оценивать вклад каждой сцены в возможные маршруты: перезапуск после портала, рикошет с нижней дуги, освобождение груза. Не требовать обязательного порядка прохождения.</li><li>Надёжно резервировать пустые коридоры и проверять весь цикл движения, а не только несколько фаз. Сейчас геометрия и нативные снимки отсекают пересечения, но полного доказательства всех фаз нет.</li><li>Мерить ритм по каждому выстрелу, полезность рикошетов, время ожидания и затраты на последние цели. Полная очистка сама по себе не доказывает удовольствие.</li><li>Учить общий планировщик выбирать словарь Blast + механическую сцену Alea + акцент разрушения, под разные плотности, симметрию и сложность. Сейчас это осмысленный первый набор из шести схем, не бесконечный универсальный словарь.</li><li>Отбирать на нескольких случайных потоках и задержках с адаптивным прицеливанием, затем сверять с короткими игровыми сессиями людей. «Фановость» и желание переигрывать здесь пока гипотезы.</li></ol>
<h2>12 процедурных уровней</h2><div class="grid">${cards}</div><h2>Все рассмотренные схемы</h2>${[['des1','/des1: все 11'],['des','/des: 8 композиций'],['gen','/gen: 8 композиций'],['main','Основной CDN-снимок: 19'],['latest','Локальный основной экспорт: 5']].map(([n,t])=>`<details><summary>${t}</summary><img class="audit" loading="lazy" src="../../quality/images/${n}.png" alt="${esc(t)}"></details>`).join('')}<details><summary>Все 292 Blast</summary><div class="gallery">${[0,75,150,225].map(i=>`<a href="../../quality/images/blast-${String(i).padStart(3,'0')}.png"><img class="audit" loading="lazy" src="../../quality/images/blast-${String(i).padStart(3,'0')}.png" alt="Blast ${i+1}–${Math.min(292,i+75)}"></a>`).join('')}</div></details><details><summary>/des1: кадры всех настоящих проходов</summary>${[0,4,8].map(i=>`<img class="audit" loading="lazy" src="../../quality/images/des1-routes-${i}.png" alt="Проходы /des1">`).join('')}</details><p><a href="../../../data/des2/proof.json">Проходы и параметры</a> · <a href="../../../data/des2/robustness.json">Отключение механик / другие старты</a> · <a href="../../../data/quality/machine.json">Прогоны исходных наборов</a> · <a href="../../../data/quality/designs.json">Вся геометрия и метрики</a> · <a href="../../../data/des2/campaign.json">Каталог /des2</a></p></main></body></html>`;
await mkdir('generators/destruction2/report',{recursive:true});await writeFile('generators/destruction2/report/index.html',html);await writeFile('data/des2/summary.json',JSON.stringify({metrics:table,oldPeaks,oldComplete:before.filter(r=>r.complete).length,selected:rows},null,2));
console.log('Report built',campaign.levels.length,'levels');
