import assert from 'node:assert/strict';
import {readFile,writeFile} from 'node:fs/promises';
import {createHash} from 'node:crypto';
import {execFileSync} from 'node:child_process';
import {generateSequence,auditSequence,materializeSequence,DEFAULT_WEIGHTS} from '../generators/destruction6/director.js';
import {resolveCampaign6} from '../generators/destruction6/client.js';
import {generateFormation,FORMS} from '../generators/destruction6/formations.js';
import {RUNTIME_SOURCES} from '../generators/destruction3/cache.mjs';
const read=async p=>JSON.parse(await readFile(p,'utf8')),hash=x=>createHash('sha256').update(x).digest('hex');
const bank=await read('data/des6/bank.json'),manifest=await read('data/des6/campaign.json'),proof=await read('data/des6/bank-proof.json');
const nativeFingerprint=hash((await Promise.all(RUNTIME_SOURCES.map(p=>readFile(p)))).join('\n')+'\nbank-policy-1');
assert.equal(proof.nativeFingerprint,nativeFingerprint,'Native proof is stale');
assert.equal(bank.fingerprint,hash(nativeFingerprint+(await readFile('generators/destruction6/profile.js'))+(await readFile('generators/destruction6/formations.js'))));
assert.equal(manifest.fingerprint,bank.fingerprint);assert.equal(bank.entries.length,proof.accepted.length);
const sources=Object.fromEntries(await Promise.all(Object.entries(bank.sources).map(async([s,r])=>{const bytes=await readFile(r.file);assert.equal(hash(bytes),r.sha256);if(s!=='fresh')assert.equal(hash(bytes),hash(execFileSync('git',['show','904efb1:'+r.file],{maxBuffer:40e6})),'Old campaign changed');return [s,JSON.parse(bytes)];})));
for(const row of proof.accepted){const l=sources[row.source].levels.find(l=>l.id===row.id);assert.equal(hash(JSON.stringify(l)),row.key,'Exact source key mismatch');assert(row.proof.complete&&row.proof.replayComplete);assert(row.proof.frames.length>=3);}
for(const l of sources.fresh.levels)assert.deepEqual(generateFormation({seed:l.metadata.generator.seed,form:l.metadata.generator.form}),l);
assert.deepEqual([...new Set(sources.fresh.levels.map(l=>l.metadata.generator.form))].sort(),FORMS.slice().sort());
const sequence=generateSequence(bank.entries,{seed:manifest.seed});assert.deepEqual(sequence.rows.map(r=>({id:r.id,source:r.source})),manifest.sequence);assert.deepEqual(sequence.quotas,DEFAULT_WEIGHTS);assert(auditSequence(sequence.rows).valid);
for(const s of ['fresh','blast','des2'])assert.equal(new Set(sequence.rows.filter(r=>r.source===s).map(r=>r.family)).size,new Set(bank.entries.filter(r=>r.source===s).map(r=>r.family)).size,'Missing formation coverage');
const output=await resolveCampaign6({manifest,bank,loadSource:file=>read(file)}),direct=materializeSequence(sequence,sources);assert.deepEqual(output.levels,direct);
for(const l of output.levels){const e=l.metadata.campaign6,original=sources[e.source].levels.find(r=>r.id===e.originalId);assert.deepEqual({...l,name:original.name,metadata:original.metadata},original,'Coordinates/rules changed during materialization');}
const runs=[];for(let i=0;i<24;i++){
 const start=performance.now(),s=generateSequence(bank.entries,{seed:'unseen-campaign-'+i});assert(s.audit.valid);runs.push({seed:s.seed,ms:performance.now()-start,ids:s.rows.map(r=>r.id),actions:s.audit.actions});
}
assert.equal(new Set(runs.map(r=>r.ids.join(','))).size,runs.length);
await writeFile('data/des6/autonomy.json',JSON.stringify({version:'0.1',fingerprint:bank.fingerprint,runs,note:'Pure deterministic campaign assembly on 24 new seeds. A finite checked bank; no new board coordinates are generated by this operation.'}));
console.log('ok',bank.entries.length,'native routes; 48 intact levels; all new families; 24 distinct client-compatible itineraries; mean ms',runs.reduce((s,r)=>s+r.ms,0)/runs.length);
