<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net472</TargetFramework>
    <LangVersion>latest</LangVersion>
    <PeggleEditRoot Condition="'$(PeggleEditRoot)' == ''">$(MSBuildThisFileDirectory)..\..\..\..\..\upstream\PeggleEdit</PeggleEditRoot>
  </PropertyGroup>
  <ItemGroup>
    <ProjectReference Include="$(PeggleEditRoot)\src\IntelOrca.PeggleEdit.Tools\IntelOrca.PeggleEdit.Tools.csproj" />
    <Reference Include="System.Web.Extensions" />
    <PackageReference Include="Microsoft.NETFramework.ReferenceAssemblies" Version="1.0.3" PrivateAssets="all" />
  </ItemGroup>
</Project>
